language: node_js

node_js:
  - "6"
services:
  - postgresql

before_install:
- npm install -g sequelize-cli@2.8.0
- npm install -g mocha

before_script:
  - npm install
  - psql -c 'create database "More-Recipes-test";' -U postgres

script: 
  - npm run test

after_success:
  - npm install codeclimate-test-reporter -g
  - npm run coverage
  
addons:
  code_climate:
    repo_token: dd54b40b786c38f51ccba46301f1e9b0a8d7c0cc5018f3f2fd6d3af9705bd8b0