language: node_js

node_js:
  - "6"

cache:
  directories:
  - "node_modules"

services:
  - postgresql

before_script: 
  - npm install
  - psql -c 'create database More-Recipes-test;' -U postgres

script: 
  - npm run test